spring:
  redis:
    database: 0
    host: 192.168.176.131
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf8
    username: root
    password: mysql
  session:
    store-type: redis
mybatis:
  type-aliases-package: com.sample.spring.boot.redis.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com:
      sample:
        spring:
          boot:
            redis: debug
